name: 1) Security Scanning

on:
    push:
        branches: main

jobs:
    sast:
        name: SAST with Semgrep
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Run Semgrep
              run: |
                    docker run --rm -v "${PWD}:/src" returntocorp/semgrep \
                    semgrep --config=p/security-audit \
                            --config=p/flask \
                            --config=p/python \
                            --severity=ERROR \
                            --json > semgrep_report.json
            
            - name: Upload Semgrep Report
              uses: actions/upload-artifact@v4
              with:
                name: semgrep-report
                path: semgrep_report.json
    
    sca:
        name: SCA with pip-audit
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Run pip-audit SCA scan
              run: |
                   docker run --rm -v "${PWD}:/app" ghcr.io/pypa/pip-audit:latest \
                   pip-audit --format json > pip-audit-report.json

            - name: Upload SCA report
              uses: actions/upload-artifact@v4
              with:
                name: pip-audit-report
                path: pip-audit-report.json

    secrets-scan:
        name: Secrets Scan (Gitleaks)
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0  # Ensures full git history for scanning

            - name: Install Gitleaks
              run: |
                curl -sSfL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_$(uname -s)_$(uname -m).tar.gz \
                | tar -xz -C /usr/local/bin gitleaks

            - name: Run Gitleaks Scan
              run: |
                gitleaks detect \
                --source . \
                --no-git \
                --report-format json \
                --report-path gitleaks-report.json

            - name: Upload Gitleaks Report
              uses: actions/upload-artifact@v4
              with:
                name: secrets-report
                path: gitleaks-report.json
