name: Build Docker Image

on:
    push:
        branches:
            - main

jobs:
    build-image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker Image
              run: docker build -t world-clock-flask:latest .

            - name: Save Docker Image as tar file
              run: docker save world-clock-flask:latest -o image-world-clock.tar

            - name: Upload image as artifact
              uses: actions/upload-artifact@v4
              with:
                name: image-tar
                path: image.tar