name: Build Docker Image

on:
    push:
        branches:
            - main

jobs:
    build-image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker Image
              run: docker build -t world-clock-flask:latest .

            - name: Save Docker Image as tar file
              run: docker save world-clock-flask:latest -o image-world-clock.tar

            - name: Upload image as artifact
              uses: actions/upload-artifact@v4
              with:
                name: image-tar
                path: image-world-clock.tar
    
    scan-image:
        name: Trivy Image Scan
        needs: build-image
        runs-on: ubuntu-latest

        steps:
            - name: Download Docker Image (tar file)
              uses: actions/download-artifact@v4
              with:
                name: image-tar
                path: .

            - name: Load Docker Image
              run: docker load -i image-world-clock.tar

            - name: Install Trivy
              run: |
                sudo apt-get update
                sudo apt-get install -y wget
                wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
                echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
                sudo apt-get update
                sudo apt-get install -y trivy


            - name: Run Trivy Scan
              run: |
                    trivy image --scanners vuln,secret,config \
                    --severity CRITICAL,HIGH \
                    --format json \
                    --output trivy-report.json \
                    world-clock-flask:latest

            - name: Upload Trivy Scan Results (JSON)
              uses: actions/upload-artifact@v4
              with:
                name: trivy-report
                path: trivy-report.json
      
    upload-image:
        name: Upload Image to ECR
        needs: scan-image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
                aws-region: us-east-1
            
            - name: Login to AWS ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
            
            - name: Set ECR_URI for later steps
              run: echo "ECR_URI=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

            - name: Download Docker Image (tar file)
              uses: actions/download-artifact@v4
              with:
                name: image-tar
                path: .

            - name: Load Docker Image
              run: docker load -i image-world-clock.tar

            - name: Tag Docker Image
              run: docker tag world-clock-flask:latest $ECR_URI/public-portfolio/world-clock-flask:latest

            - name: Push Image to ECR
              run: docker push $ECR_URI/public-portfolio/world-clock-flask:latest